/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AreasHealthcareRouteImport } from './routes/areas/healthcare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasHealthcareRoute = AreasHealthcareRouteImport.update({
  id: '/areas/healthcare',
  path: '/areas/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas/healthcare': typeof AreasHealthcareRoute
  '/contact': typeof ContactIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas/healthcare': typeof AreasHealthcareRoute
  '/contact': typeof ContactIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas/healthcare': typeof AreasHealthcareRoute
  '/contact/': typeof ContactIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/areas/healthcare' | '/contact'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/areas/healthcare' | '/contact'
  id: '__root__' | '/' | '/areas/healthcare' | '/contact/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasHealthcareRoute: typeof AreasHealthcareRoute
  ContactIndexRoute: typeof ContactIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/healthcare': {
      id: '/areas/healthcare'
      path: '/areas/healthcare'
      fullPath: '/areas/healthcare'
      preLoaderRoute: typeof AreasHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasHealthcareRoute: AreasHealthcareRoute,
  ContactIndexRoute: ContactIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
